### ISSUE TITLE
Unable to analyse

### ISSUE THREAD

**Issue by MSNarry** [schollz/find3#146]
I have find3 with go1.6 in an Ubuntu 16.0.4 machine, I am able to run the server, both the ai and the main, but when I try to include new measurements with the testing functionalities it has errors: " analysis.go AnalyzeSensorData:222 unable to analyze: could not find '/home/go/src/github.com/schollz/find3/server/main/data/zxo1qZZb.find3.ai'". It happens when using both the comands:

python3 submit_jsons.py http://localhost:8005 testdb.learn.1439597065993.jsons

and 

sh learn.sh

when running the last one it outputs : "{"message":"inserted data","success":true}", but it apperars the error. Also when trying to access with the browser to "localhost:8005/view/location/testdb/zack". It stops the main server with the following message: 

panic: interface conversion: interface {} is string, not []uint8

goroutine 12422 [running]:
github.com/schollz/find3/server/main/src/database.(*Database).getRows(0xc00014c840, 0xc0006e9e00, 0xc0006e9e00, 0xc000b65e10, 0x1, 0x1, 0xc0006e9e00)
	/home/VICOMTECH/msanz/go/src/github.com/schollz/find3/server/main/src/database/db.go:1097 +0xf84
github.com/schollz/find3/server/main/src/database.(*Database).GetAllFromPreparedQuery(0xc00014c840, 0xd316dd, 0x46, 0xc000b65e10, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/VICOMTECH/msanz/go/src/github.com/schollz/find3/server/main/src/database/db.go:1044 +0x18b
github.com/schollz/find3/server/main/src/database.(*Database).GetLatest(0xc00014c840, 0xc0008868af, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/VICOMTECH/msanz/go/src/github.com/schollz/find3/server/main/src/database/db.go:641 +0x11a
github.com/schollz/find3/server/main/src/server.sendOutLocation(0xc0008868bb, 0x6, 0xc0008868af, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/VICOMTECH/msanz/go/src/github.com/schollz/find3/server/main/src/server/server.go:870 +0x10b
created by github.com/schollz/find3/server/main/src/server.wshandler
	/home/VICOMTECH/msanz/go/src/github.com/schollz/find3/server/main/src/server/websockets.go:66 +0x46a

**Comment by MSNarry** [comment]
I found in the same directory a file with the same name as the required one but with different extension as it is a database being : "zxo1qZZb.sqlite3.db". Coud it be that some file is not generated or the version I have is not well installed?
